apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e98ux1r12-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-feadf363cc.a3a4.p3.openshiftapps.com/rhtap/rhtap-qe:8e7ecb90594408ac5fb3f3e4654f0e16fc1ea466@sha256:147efbf4220f33138309fcf9f56dbb4e297543ce4b5ccf9129c09d6b3c324931
          name: container-image
